---
root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
#  - jest
extends:
  - "./node_modules/gts/"
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
#  - plugin:jest/recommended
  - prettier
